<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <DefaultItemExcludes>$(DefaultItemExcludes);DataSeries\bin\**;DataSeries\obj\**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="ScottPlot.Avalonia" Version="5.1.59" />
        <PackageReference Include="Sesame.ScottPlot.Avalonia" Version="5.1.58" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Programa.cs" />
  </ItemGroup>

  <ItemGroup>
  <None Include="weather_data.csv">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
</Project>
